<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMsp1YFL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMsp1YFL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMsp1YFL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMsp1YFL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMsp1YFL\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'Msp1YFL',
    'container.build_id' => '64d09e28',
    'container.build_time' => 1550688085,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMsp1YFL');
