<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGSDplcx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGSDplcx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGSDplcx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGSDplcx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGSDplcx\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'GSDplcx',
    'container.build_id' => '1b59a38d',
    'container.build_time' => 1548744894,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGSDplcx');
