<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPLH1Vv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPLH1Vv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPLH1Vv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPLH1Vv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWPLH1Vv\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'WPLH1Vv',
    'container.build_id' => '837a977c',
    'container.build_time' => 1550746730,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPLH1Vv');
